outscale/cluster-api-provider-outscale

- cloud/services/security/mock_security/publicip_mock.go
- cloud/services/security/publicip.go
- controllers/osccluster_controller.go
- controllers/osccluster_internetservice_controller.go
- controllers/osccluster_internetservice_controller_unit_test.go
- controllers/osccluster_natservice_controller.go
- controllers/osccluster_natservice_controller_unit_test.go
- controllers/osccluster_net_controller.go
- controllers/osccluster_net_controller_unit_test.go
- controllers/osccluster_publicip_controller.go
- controllers/osccluster_publicip_controller_unit_test.go
- controllers/osccluster_routetable_controller.go
- controllers/osccluster_routetable_controller_unit_test.go
- controllers/osccluster_securitygroup_controller.go
- controllers/osccluster_subnet_controller.go
- controllers/osccluster_subnet_controller_unit_test.go
Add natservice and publicip unit test:
* Integrate service publicipsvc
* Use publicipsvc instead of securitysvc
* Add publicip unit test
* Integrate service publicipsvc
* Use natservicesvc instead of securitysvc
* Add natservice unit test
* Use setup and setupmock
* Use assert
> Add natservice and publicip unit test

- api/v1beta1/types.go
- cloud/services/service/load_balancer.go
- controllers/osccluster_controller.go
- controllers/osccluster_loadbalancer_controller.go
- controllers/osccluster_loadbalancer_controller_unit_test.go
- controllers/osccluster_securitygroup_controller.go
- controllers/osccluster_securitygroup_controller_unit_test.go
- go.mod
- go.sum
Add securitygroup and loadbalancer unit test:
* Integrate service loadbalancersvc
* Use loadbalancersvc instead of servicesvc
* Add loadbalancer unit test
* Integrate service securitygroupsvc in osccluster_controller
* Use securitygroupsvc instead of securitysvc
* add securityGroup unit test
* Use  setup and setupmock
* Use assert
> Add securitygroup and loadbalancer unit test

- .github/workflows/build.yaml
- .github/workflows/unit-func-e2e-test.yaml
- Makefile
- api/v1beta1/types.go
- cloud/scope/cluster.go
- cloud/scope/machine.go
- cloud/services/service/load_balancer.go
- controllers/osccluster_loadbalancer_controller.go
- controllers/oscmachine_controller.go
- controllers/oscmachine_vm_controller.go
- example/cluster-machine-template-simple.yaml
- testenv/osccluster_controller_test.go
- testenv/value
Add functional test for machine controller
> Testenv machine

- .github/workflows/unit-func-e2e-test.yaml
> Use multi github env to fix e2etest launch

- .github/workflows/unit-func-e2e-test.yaml
- Makefile
- docs/develop.md
- hack/ensure-clusterctl.sh
- hack/ensure-controller-gen.sh
- hack/ensure-envsubst.sh
- hack/ensure-envtest.sh
- hack/ensure-gh.sh
- hack/ensure-go.sh
- hack/ensure-helm.sh
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
- hack/ensure-kustomize.sh
- hack/ensure-mockgen.sh
- hack/ensure-packer.sh
- hack/ensure-tilt.sh
- hack/releasechangelog.sh
* verify and install kubectl, clusterctl, controller-gen, mockgen, envsubst, testenv, helm, kind, kustomize, packer
> Validate binary

- .github/workflows/unit-func-e2e-test.yaml
/kind bug    
Have more log for failure stack.
Fixes #
**TODOs**:
> Have more log failure stack.

- .github/workflows/unit-func-e2e-test.yaml
/kind bug    
Get logs from testenv
Fixes #
**TODOs**:
> Get logs functional test

- .github/workflows/unit-func-e2e-test.yaml
Recue vm size
Fixes #
**TODOs**:
> Reduce vm size

- .github/workflows/unit-func-e2e-test.yaml
/kind bug 
cleanup quota
Fixes #
**TODOs**:
> Reduce vms

- Makefile
- Tiltfile
- tilt.json
>  Refactor tiltfile

- .github/workflows/unit-func-e2e-test.yaml
- Makefile
- api/v1beta1/types.go
- go.mod
- go.sum
- test/e2e/config/outscale.yaml
- testclean/basic_test.go
- testclean/cluster.go
- testclean/kubeadmControlPlane.go
- testclean/machine.go
- testclean/machineDeployment.go
- testclean/namespace.go
- testclean/osccluster.go
- testclean/oscmachine.go
- testclean/suite_test.go
- testenv/osccluster_controller_test.go
/kind feature 
Script to clean stack 
Fixes #
**TODOs**:
> Add testclean

- cloud/services/compute/image.go
- cloud/services/compute/mock_compute/image_mock.go
- controllers/oscmachine_image_controller.go
- controllers/oscmachine_image_controller_unit_test.go
Signed-off-by: outscale_hmi <hanen.mizouni@outscale.com>
> add getImageId for imageController

- .github/workflows/release.yml
/kind bug   
use docker hub
Fixes #
**TODOs**:
> For dockerhub

- Makefile
- helm/clusterapioutscale/templates/validate_webhook.yaml
- testclean/machine.go
/kind bug    
Update helm charts for webhook
Fixes #
**TODOs**:
> Update helm charts and testclean

- .github/workflows/release.yml
- helm/clusterapioutscale/values.yaml
/kind bug     
Change release 
Fixes #
**TODOs**:
> Add release

- docs/src/topics/get-started-with-clusterctl.md
- templates/cluster-template.yaml
/kind bug  
Add image config
Fixes #
**TODOs**:
> Have image_name configurable

- controllers/oscmachine_vm_controller_unit_test.go
Add missing vm unit test
Add missing vm test
Fixes #
**TODOs**:
> Add missing vm test

- .github/workflows/publish_doc.yaml
/kind bug   
Fix doc link
Fixes #
**TODOs**:
> Use doc branch

- .github/workflows/publish_doc.yaml
/kind bug   
use master instead of main 
Fixes #
**TODOs**:
> Use main instead of master in publish

- docs/src/topics/get-started-with-clusterctl.md
/kind bug
fix doc link
Fixes #
**TODOs**:
> Update link doc

- metadata.yaml
/kind bug 
To use latest and integrate clusterctl
Fixes #
**TODOs**:
> Fix metadata

- .github/workflows/conformance.yaml
- .github/workflows/kind.yaml
- .github/workflows/release.yml
- .github/workflows/unit-func-e2e-test.yaml
- Dockerfile
- Makefile
- Tiltfile
- cloud/scope/clients.go
- config/default/manager_auth_proxy_patch.yaml
- helm/clusterapioutscale/README.md
- helm/clusterapioutscale/templates/deployment.yaml
- helm/clusterapioutscale/values.yaml
* add user agent
* add version
* add version test
/kind feature   
Add user agent to catch hen cluster api is used.
Fixes #
**TODOs**:
> Add user agent:

- cloud/scope/clients.go
> Default version dev

- .github/workflows/publish_doc.yaml
- README.md
- docs/src/developers/e2e.md
- docs/src/developers/releases.md
/kind bug               
Change bucket region 
Fixes #
**TODOs**:
> Change bucket region

- test/e2e/config/outscale.yaml
/kind bug    
Changes keypair name 
Fixes #
**TODOs**:
> Change keypair

- .github/workflows/conformance.yaml
- .github/workflows/image-builder.yaml
- .github/workflows/kind.yaml
/kind bug  
Missing frieza
https://github.com/outscale-dev/cluster-api-provider-outscale/issues/149
**TODOs**:
> Missing frieza

- cloud/services/compute/vm.go
- controllers/oscmachine_vm_controller.go
- controllers/oscmachine_vm_controller_unit_test.go
/kind bug 
Fix current release in cloudgov
Fixes #188 
**TODOs**:
> Wait before check the first time vm status

- docs/src/topics/omi.md
/kind documentation 
Add cloudgov image 
Fixes #
**TODOs**:
> Add cloudgov

- .github/workflows/unit-func-e2e-test.yaml
> switch pull request

- controllers/osccluster_controller.go
- controllers/osccluster_internetservice_controller.go
- controllers/osccluster_loadbalancer_controller.go
- controllers/osccluster_natservice_controller.go
- controllers/osccluster_net_controller.go
- controllers/osccluster_publicip_controller.go
- controllers/osccluster_routetable_controller.go
- controllers/osccluster_securitygroup_controller.go
- controllers/osccluster_subnet_controller.go
- controllers/oscmachine_controller.go
- controllers/oscmachine_image_controller.go
- controllers/oscmachine_keypair_controller.go
- controllers/oscmachine_vm_controller.go
- controllers/oscmachine_volume_controller.go
- controllers/oscmachinetemplate_capacity_controller.go
- controllers/oscmachinetemplate_controller.go
/kind cleanup    
Change verbosity.
Fixes # https://github.com/outscale-dev/cluster-api-provider-outscale/issues/108
**TODOs**:
> Change verbosity

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/json-format-pull-request.yaml
- .github/workflows/unit-func-e2e-test.yaml
- .gitignore
- hack/json-format/Cargo.toml
- hack/json-format/Makefile
- hack/json-format/run-integration-test.sh
- hack/json-format/src/core.rs
- hack/json-format/src/input.rs
- hack/json-format/src/lib.rs
- hack/json-format/src/main.rs
- hack/json-format/tests/integration_test.rs
/kind feature    
Format json for image builder
Fixes #
**TODOs**:
> Json format

- testclean/basic_test.go
- testclean/kubeadmControlPlane.go
- testclean/machine.go
- testclean/namespace.go
- testclean/osccluster.go
- testclean/oscmachine.go
- testclean/oscmachinetemplate.go
/kind feature 
Handle oscmachinetemplate
Fixes #212 
**TODOs**:
> Add oscmachinetemplate in testclean

- docs/src/SUMMARY.md
- docs/src/introduction.md
> Not use readme for bucket website

- example/cluster-machine-template-default.yaml
- example/cluster-machine-template-simple.yaml
- test/e2e/config/outscale.yaml
- testenv/osccluster_controller_test.go
/kind other 
Migrate to gp2 
**TODOs**:
> Migrate to GP2 instead of io1

- api/v1beta1/oscmachine_validation.go
- api/v1beta1/oscmachine_webhook_test.go
- controllers/oscmachine_vm_controller.go
- controllers/oscmachine_vm_controller_unit_test.go
check ratio iops/size
Closes #216 
check ratio iops/size is less than 300
Fixes #216 
**TODOs**:
> check ratio iops/size

- .github/workflows/unit-func-e2e-test.yaml
/kind bug    
Buildkit need to have now docker-buildx-plugin 
Fixes #
**TODOs**:
> Missing docker-buildx-plugin

- .github/workflows/unit-func-e2e-test.yaml
- Makefile
/kind bug 
Fix ci with docker buildx
Fixes #
https://github.com/docker/buildx/issues/318
**TODOs**:
> Add buildx load to fix ci

- helm/clusterapioutscale/README.md
- helm/clusterapioutscale/templates/deployment.yaml
- helm/clusterapioutscale/values.yaml
/kind feature    
Select log level and backoff parameters in helm charts.
Closes #226  
Fixes #226 
**TODOs**:
> Choose backoff and log level

- .github/workflows/dispatch_image_builder.yaml
/kind bug    
Retrieve image  name instead of array
Fixes #
**TODOs**:
> Retrieve image

- .github/scripts/launch.sh
- .github/workflows/dispatch_image_builder.yaml
/kind other  
Migrate to kubernetes-sigs/image-builder
> Migrate to kubernetes-sigs/image-builder

- docs/src/topics/get-started-with-clusterctl.md
- metadata.yaml
- test/e2e/config/outscale.yaml
- testenv/osccluster_controller_test.go
Fix: fix ci and doc and metadata
> Fix: fix ci and doc and metadata

- cloud/services/security/securitygroup.go
/bug
Bad tag value for MainK8sSg
> fix: Use True instead of own for MainK8sSg tag

- api/v1beta1/types.go
- example/cluster-machine-template-bastion.yaml
- example/cluster-machine-template-simple.yaml
/kind feature 
Add missing port for flannel and calico
> Feat: Set default port for flannel and calico

- .github/workflows/conformance.yaml
- .github/workflows/kind.yaml
- cloud/services/compute/vm.go
/kind bug     
Have ccm available 
Fixes #257 
Fixes #255
> Typo tag ccm and fix kustomize version

- example/talos/bastion/gen-wg-keypair.sh
> Add boilerplate

- .github/workflows/conformance.yaml
- .github/workflows/kind.yaml
- .github/workflows/unit-func-e2e-test.yaml
- api/v1beta1/oscmachine_validation.go
- api/v1beta1/oscmachinetemplate_webhook_test.go
- api/v1beta1/types.go
- controllers/osccluster_bastion_controller_unit_test.go
- controllers/oscmachine_vm_controller_unit_test.go
- controllers/oscmachinetemplate_capacity_controller_unit_test.go
- docs/src/topics/config.md
- example/cluster-machine-template-bastion.yaml
- example/cluster-machine-template-default.yaml
- example/cluster-machine-template-simple.yaml
- example/hello-osc.yaml
- example/microk8s.yaml
- example/talos/talos.yaml
- test/e2e/config/outscale.yaml
- testenv/osccluster_controller_test.go
/kind feature 
Add tinav6
Fixes #269
> Add tinav6 and migrate to tinav6

- metadata.yaml
> Prepare release

- api/v1beta1/types.go
- capm.yaml
- cloud/scope/cluster.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_oscclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_oscclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachinetemplates.yaml
- controllers/osccluster_bastion_controller.go
- controllers/osccluster_bastion_controller_unit_test.go
- docs/src/topics/get-started-with-clusterctl.md
- example/cluster-machine-template-bastion.yaml
/kind Bug
Adding publicIpName to bastion after creation does not link public to VM
Fixes #297
> Can link publicIpName after bastion is created

- docs/src/SUMMARY.md
- docs/src/developers/release-custom-omi-ubuntu.md
- docs/src/topics/omi.md
- docs/src/topics/upgrade-cluster.md
> Upgrade doc cluster

- capm.yaml
> fix image capm

- docs/src/topics/change-providerid.md
I just tested it, and it worked really well this way.
Thanks for the initial doc!
> doc: improve doc about providerId upgrade

- docs/src/topics/get-started-with-clusterctl.md
> Update Cilium Link

- controllers/oscmachine_controller.go
/kind bug               Fixes a nilPointer when vmstate is not yet available
Fixes #345
**TODOs**:
> fix(oscmachine): vmstate is nil

- cloud/services/security/securitygroup.go
/kind bug               Fixes a SecurityGroup rules reconcile with DNS IpPrococol and PortRange limit enforced to -1
Fixes #346
**TODOs**:
> fix(cluster): security group rules reconcile

- helm/clusterapioutscale/templates/proxy_clusterrolebinding.yaml
We reference a clusterRoleBinding instead of clusterRole
> Fix Helm deploy

- controllers/osccluster_bastion_controller.go
- controllers/osccluster_controller.go
- controllers/osccluster_loadbalancer_controller.go
- controllers/osccluster_natservice_controller.go
- controllers/osccluster_publicip_controller.go
- controllers/osccluster_routetable_controller.go
- controllers/osccluster_securitygroup_controller.go
- controllers/osccluster_subnet_controller.go
- controllers/oscmachine_vm_controller.go
- controllers/oscmachine_volume_controller.go
- testenv/osccluster_controller_test.go
No need to define a Contains func, use slices.Contains instead.
> ♻️ refacto: no need for Contains

- controllers/oscmachine_keypair_controller.go
- controllers/oscmachine_keypair_unit_test.go
> 🐛 fix/oscmachine: VMs without keypair cannot be deleted

- controllers/oscmachine_controller_test.go
- controllers/oscmachine_helpers_test.go
- controllers/oscmachine_vm_controller.go
> 🐛 fix/oscmachine: vm were recreated after a clusterctl move

- Dockerfile
> 🧱 docker: switch to distroless + strip binary

- docs/src/topics/config-cluster.md
Some tables were broken
---
---
---
---
---
> 📝 doc: fix table formatting

- github_actions/deploy_cluster/Dockerfile
Looks like the old urls are broken.
---
---
---
---
---
> 👷 ci: update helm installation in local action

- README.md
- docs/src/developers/releases.md
- docs/src/topics/get-started-with-clusterctl.md
Documentation updates.
Please check the relevant option(s):
Please describe the test strategy:
> 📝 doc: updates (installation, maturity level)
