outscale/cluster-api-provider-outscale

controllers/osccluster_internetservice_controller.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_natservice_controller.go, controllers/osccluster_publicip_controller.go, controllers/osccluster_routetable_controller.go, controllers/osccluster_securitygroup_controller.go, controllers/osccluster_subnet_controller.go, example/cluster-template-default.yaml
- Only set default value of the current object not the other dependancies.
- Missing to set default value in reconcileDelete function.
- add exemple of cluster-template with only net name (to check if default value work)
=> Add cluster-template-default and clean/fix reconcile/reconcileDelete

controllers/osccluster_net_controller_unit_test.go, controllers/osccluster_subnet_controller_unit_test.go
* Each test will or not use only mock that it needs.
* GetRessourceId failure will not use mock.
* Use gomock.Eq
* Change also format.
=> Split each reconcile test into three

.github/workflows/conformance.yaml, .github/workflows/kind.yaml, .github/workflows/unit-func-e2e-test.yaml
When the cloud account will be migrating, the ID of the OMI will change, theses changes will make that transparent
Canceling Ci because it will not take into account these changes
=> Upgrade Github CI to use default OMI_ID

controllers/osccluster_publicip_controller_unit_test.go, controllers/osccluster_securitygroup_controller_unit_test.go, controllers/oscmachine_image_controller_unit_test.go, controllers/oscmachine_keypair_unit_test.go
/kind cleanup  
We have to improve our code coverage for unit test (https://github.com/outscale-dev/cluster-api-provider-outscale/pull/151)
Fixes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/164
It also cover unit test for this PR.
**TODOs**:
- [x ] adds unit tests
=> Improve unit test  code coverage for  image, publicip, securitygroup, keypair

.github/scripts/git_command.sh, .github/scripts/launch.sh, .github/workflows/build.yaml, .github/workflows/image-builder.yaml, .github/workflows/unit-func-e2e-test.yaml, Makefile, docs/src/topics/omi.md
/kind feature   
Auto generate docs version.
Fixes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/160
**TODOs**:
=> Autogenerate docs

.github/workflows/build.yaml, Makefile, docs/src/developers/developement.md, docs/src/developers/e2e.md, docs/src/topics/get-started-with-clusterctl.md, hack/ensure-controller-gen.sh, hack/ensure-envsubst.sh, hack/ensure-envtest.sh, hack/ensure-go.sh, hack/ensure-golangci-lint.sh, hack/ensure-mockgen.sh, hack/ensure-yamlfmt.sh, hack/verify-boilerplate.sh
/kind cleanup   
We refactor to use gopath instead.
Fixes #107
**TODOs**:
=> Change gopath

controllers/oscmachine_vm_controller.go, controllers/oscmachine_vm_controller_unit_test.go
/kind bug  
Fix lockup time with cloudgov plateform.
Fixes #188 
Fix lockup time with cloudgov plateform.
**TODOs**:
=> Increase lockup time

Makefile, api/v1beta1/types.go, cloud/scope/machine.go, cloud/services/net/mock_net/natservice_mock.go, cloud/services/net/natservice.go, cloud/services/security/keypair.go, cloud/services/service/load_balancer.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_loadbalancer_controller_unit_test.go, controllers/osccluster_natservice_controller.go, controllers/osccluster_natservice_controller_unit_test.go, controllers/osccluster_securitygroup_controller.go, controllers/osccluster_securitygroup_controller_unit_test.go, controllers/oscmachine_vm_controller.go, controllers/oscmachine_vm_controller_unit_test.go, example/cluster-machine-template-default.yaml, example/cluster-machine-template-simple.yaml, templates/cluster-template.yaml, testenv/osccluster_controller_test.go, testenv/suite_test.go, testenv/value
/kind bug   
Delete vm (for vm and loadbalancer) can be too long so it can execeded timeout.
Machine should be able to be destroyed with any state (provisioning, provisioned, running)
Also to have idempotency vm functions
Fixes #173
Fixes #106
It incluse also vm unit test refacto.
**TODOs**:
=> Change lbu timeout

cloud/scope/machine.go, controllers/oscmachine_vm_controller.go, docs/src/topics/get-started-with-clusterctl.md, example/cluster-machine-template-default.yaml, example/cluster-machine-template-simple.yaml, example/hello-osc.yaml, templates/cluster-template.yaml, test/e2e/config/outscale.yaml, test/e2e/data/infrastructure-outscale/cluster-template-kcp-remediation.yaml, test/e2e/data/infrastructure-outscale/cluster-template-md-remediation.yaml, test/e2e/data/infrastructure-outscale/cluster-template-node-drain.yaml, test/e2e/data/infrastructure-outscale/cluster-template-upgrade-scale-in.yaml, test/e2e/data/infrastructure-outscale/cluster-template-upgrade.yaml, test/e2e/data/infrastructure-outscale/cluster-template-with-clusterclass.yaml, test/e2e/suite_test.go, testenv/value, testenv/value-envsubst
/kind bug     
Migrate cloudProviderId from osc:// to aws:///
Fixes #196 
**TODOs**:
=> Migrate cloudProviderId

.github/scripts/git_command.sh, .github/scripts/launch.sh, .github/workflows/image-builder.yaml, Makefile
/kind feature
Release image in cloudgouv region
Fixes #189 
Fixes #181 
**TODOs**:
=> Multi region

Makefile, cloud/services/compute/image.go, cloud/services/compute/vm.go, cloud/services/net/internetservice.go, cloud/services/net/natservice.go, cloud/services/net/net.go, cloud/services/net/subnet.go, cloud/services/security/keypair.go, cloud/services/security/publicip.go, cloud/services/security/route.go, cloud/services/security/securitygroup.go, cloud/services/service/load_balancer.go, cloud/services/storage/volume.go, cloud/tag/tag.go, controllers/osccluster_securitygroup_controller.go, controllers/oscmachine_image_controller_unit_test.go, main.go, util/reconciler/defaults.go
/kind feature   
To handle throttling
Fixes #3 
It handle code error and code type.
No Mock.
First version that will be changes when throttling will have more restrict rules.
**TODOs**:
=> Handle throttling

api/v1beta1/types.go, controllers/osccluster_natservice_controller_unit_test.go, controllers/osccluster_net_controller_unit_test.go, controllers/osccluster_securitygroup_controller_unit_test.go, example/cluster-machine-template-simple.yaml, testenv/osccluster_controller_test.go, testenv/value
Signed-off-by: outscale_hmi <hanen.mizouni@outscale.com>
=> update default architecture and remove Nat subnet

.github/workflows/image-clean.yaml
Bugfix
image-clean does not use the same region as ci.
=> Clean images in the right region

.github/workflows/dispatch_image_builder.yaml
/kind feature
It add github action to launch the creation of newest image trigger by event.
Fixes #154
**TODOs**:
=> Launch image builder based on image version

capm.yaml, config/default/manager_auth_proxy_patch.yaml, controllers/osccluster_bastion_controller.go, controllers/osccluster_internetservice_controller.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_natservice_controller.go, controllers/osccluster_net_controller.go, controllers/osccluster_publicip_controller.go, controllers/osccluster_routetable_controller.go, controllers/osccluster_securitygroup_controller.go, controllers/osccluster_subnet_controller.go, controllers/oscmachine_image_controller.go, controllers/oscmachine_keypair_controller.go, controllers/oscmachine_vm_controller.go, controllers/oscmachine_volume_controller.go, controllers/oscmachinetemplate_controller.go, main.go
/kind cleanup  
Rework logs and improve logs format
Close #207 
Fixes #207 
**TODOs**:
=> Rework Logs content and Format

api/v1beta1/osccluster_types.go, cloud/services/net/internetservice.go, cloud/tag/tag.go, controllers/osccluster_internetservice_controller.go, controllers/oscmachine_vm_controller_unit_test.go
/kind cleanup    
homogenize boilerplate 
**TODOs**:
=> Update boilerplate format

api/v1beta1/types.go, controllers/osccluster_securitygroup_controller_unit_test.go, controllers/oscmachine_vm_controller.go, controllers/oscmachine_vm_controller_unit_test.go, example/cluster-machine-template-simple.yaml, example/microk8s.yaml
/kind feature 
Expose node ip address for machine in status (which is used by microK8s bootstrapper)
Open missing flux
And add example for microk8s.
Closes #222 
**Which issue(s) this PR fixes** :
Fixes #222 
Optional addresses
https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html
**TODOs**:
=> Expose Status machine adresss ip

cloud/services/service/load_balancer.go, cloud/services/service/mock_service/loadbalancer_mock.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_loadbalancer_controller_unit_test.go
/kind feature
Not having two cluster with the same loadBalancer Name.
Closes #230 
Fixes #230 
**TODOs**:
=> Have unique loadbalancer

example/talos/README.md, example/talos/bastion/bastion.tf, example/talos/bastion/gen-wg-keypair.sh, example/talos/bastion/terraform.tfvars, example/talos/bastion/user-data.sh.tftpl, example/talos/talos.yaml
/kind feature   
Add talos bootstrapper
Fixes #263
=> Add talos 

example/cluster-machine-template-simple-taint.yaml
/kind documentation
Add example of taint
Fixes #268
=> Add taint cluster-api

hack/json-format/run-integration-test.sh, hack/json-format/src/core.rs, hack/json-format/tests/integration_test.rs
/kind api-change 
Kubernetes change repo for artefact. (https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) The repo change in image-builder but not the version format.
(https://github.com/kubernetes-sigs/image-builder/commit/5761d5e6026938a71584c7c2672ae718436f211d)
=> Kubernetes change rpm and deb repo

controllers/oscmachine_controller.go, controllers/oscmachine_keypair_controller.go, controllers/oscmachine_keypair_unit_test.go
/kind bug   
Check keypair name is the same in vm and keypair section
Fixes #312 
Closes #312
=> Check keypair name is the same in vm and keypair section

controllers/oscmachine_vm_controller.go, example/rke2/ccm-rke2.yaml, example/rke2/image-builder/script/bootstrap.sh, example/rke2/osc-rke2-clusterctl.yaml
=> Expose PublicIp for Node

controllers/osccluster_controller.go, controllers/oscmachine_controller.go, controllers/oscmachinetemplate_capacity_controller.go, example/cluster-machine-template-simple.yaml, helm/clusterapioutscale/Chart.yaml, helm/clusterapioutscale/templates/deployment.yaml, helm/clusterapioutscale/values.yaml, main.go, testclean/suite_test.go, testenv/suite_test.go
/kind feature           Add support of watch-filter cluster-api arg
Implement the multi controller instance as describe here by cluster-api
Fixes #330 
Change contrller image;
**TODOs**:
=> Feat(cluster-api): add watch filter arg

controllers/oscmachinetemplate_capacity_controller.go
/kind bug               Fixes nilPointer on oscMachineTemlate capacity controller
Fixes #341
**TODOs**:
=> fix(oscMachineTemplate): Nil pointer due to error not managed

controllers/osccluster_securitygroup_controller.go
/kind bug               Fixes securityGroup creation with flag extraSecurityGroupRule enabled
Fixes #351
**TODOs**:
=> fix(securityGroup): create group whit flag extraSecurityGroupRule

controllers/osccluster_controller.go, controllers/oscmachinetemplate_capacity_controller_unit_test.go
/kind bug Fixes a loadBalancer reconcile error not catched.
Fixes #
**TODOs**:
=> fix loadBalancer error not catched

.github/scripts/cleanup_k8s_crds.sh, .github/workflows/unit-func-e2e-test.yaml
Only destroying the cluster is not enough, some CRDs or resources might have finalizers that prevent deletion. 
Example in the CI we have "oscclusters.infrastructure.cluster.x-k8s.io "cluster-api-test" already exists" (https://github.com/outscale/cluster-api-provider-outscale/actions/runs/11900884246/job/33185403408) 
So 
we need to patch cluster and osccluster to ensure that all the Custom Resource Definitions (CRDs) and their associated resources like clusters are cleaned up completely during CI runs,
=>  ensure the deletion of capi resources in githubactions

example/metalLb/Readme.md, example/metalLb/metalLb.yaml, example/metalLb/service.yaml
This PR is about : 
- Adding an example configuration for deploying a Kubernetes cluster using Cluster API.
- Including MetalLB setup and configuration instructions.
- Documenting steps to deploy a LoadBalancer service with MetalLB.
=> docs: Add example for Cluster API with MetalLB integration

.github/workflows/docker.yaml
To reduce redundant downloads and avoid rate limits, added caching for the Trivy vulnerability database in the CI workflow. 
This change speeds up the Trivy scan step by using a cached version of the database if available, minimizing network requests and improving overall workflow performance. 
The cache is refreshed as needed, ensuring up-to-date vulnerability data.
=> Add caching for Trivy vulnerability database to optimize scans

api/v1beta1/types.go, cloud/scope/cluster.go, cloud/scope/machine.go, cloud/services/compute/mock_compute/vm_mock.go, cloud/services/compute/vm.go, config/crd/bases/infrastructure.cluster.x-k8s.io_oscclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachinetemplates.yaml, config/rbac/role.yaml, controllers/osccluster_bastion_controller.go, controllers/osccluster_bastion_controller_unit_test.go, controllers/osccluster_controller.go, controllers/oscmachine_controller.go, controllers/oscmachine_vm_controller.go, controllers/oscmachine_vm_controller_unit_test.go, controllers/oscmachine_volume_controller_unit_test.go, controllers/oscmachinetemplate_capacity_controller.go, docs/src/topics/get-started-with-clusterctl.md
Unit test in bastion are updated, still missing some usecases 
reconcileVm is factorized
See https://github.com/outscale/cluster-api-provider-outscale/pull/370
Rework of the vm and bastion reconcilers so that they are more robust and stable.
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/364
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/363
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/362
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/353
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/350
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/294
fixes https://github.com/outscale/cluster-api-provider-outscale/issues/293
=> Rework reconcileVm and reconcileBastion

Makefile
Including GOFLAGS=-mod=readonly ensures a disciplined build process and aligns with best practices for reliable dependency management
=> Setting -mod=readonly ensures go modules  are not inadvertently modified during builds or tests.

helm/clusterapioutscale/templates/deployment.yaml
Helm chart default values add the securityContext 'allowPrivilegeEscalation: false' which is also the case hardcoded in the deployment template. This result to the following error when installing the chart with default values:
mapping key "allowPrivilegeEscalation" already defined
Fixed by removing the hardcoded value in templates to rely on values.yaml only
/kind bug               Fixes a newly discovered bug.
Default values for helm chart doesn't work
Fixes #406
**TODOs**:
=> Fix helm chart with default values

helm/clusterapioutscale/Chart.yaml, helm/clusterapioutscale/README.md, helm/clusterapioutscale/deploy.md, helm/clusterapioutscale/templates/_helpers.tpl, helm/clusterapioutscale/templates/certificate.yaml, helm/clusterapioutscale/templates/configmap.yaml, helm/clusterapioutscale/templates/crd.yaml, helm/clusterapioutscale/templates/deployment.yaml, helm/clusterapioutscale/templates/issuer.yaml, helm/clusterapioutscale/templates/leader-election-role.yaml, helm/clusterapioutscale/templates/leader-election-rolebinding.yaml, helm/clusterapioutscale/templates/manager_clusterrole.yaml, helm/clusterapioutscale/templates/manager_clusterrolebinding.yaml, helm/clusterapioutscale/templates/metrics_clusterrole.yaml, helm/clusterapioutscale/templates/mutating_webhook.yaml, helm/clusterapioutscale/templates/proxy_clusterrole.yaml, helm/clusterapioutscale/templates/proxy_clusterrolebinding.yaml, helm/clusterapioutscale/templates/service.yaml, helm/clusterapioutscale/templates/serviceaccount.yaml, helm/clusterapioutscale/templates/validate_webhook.yaml, helm/clusterapioutscale/templates/webhook_service.yaml, helm/clusterapioutscale/values.yaml
To follow Helm best practices, flatten values tree & use camelCase.
A validation webhook did not point to the right service and some rbac rules were missing.
=> 🐛 fix/helm: refactor values, fix validation webhook, rbac

cloud/scope/cluster.go, cloud/scope/machine.go, controllers/osccluster_controller.go, controllers/oscmachine_controller.go
MachineTemplateScope is fixed in another PR
=> 🚨 lint: XxxScope.Close() should forward context

cloud/scope/machinetemplate.go, controllers/oscmachinetemplate_controller.go
* If cluster ressources are deleted before oscmachinetemplate, oscmachinetemplate could not be deleted,
* The finalizer added was not the same that the finalizer removed => a finalizer was kept, leading to a never deleted resource
As oscmachinetemplate do not create anything, there is no need for finalizers & delete reconciliation. We stop setting it (but keep removing the one that previously set for compatibility purposes).
=> 🐛 fix: unable to delete oscmachinetemplate

helm/clusterapioutscale/templates/deployment.yaml
Moving the --watch-filter argument from kube-rbac-proxy container to manager one to be really applied
/kind bug
Fixing the helm chart when used with a given argument (watchFilter)
Fixes #442
**TODOs**:
=> fix(helm): Fix watch-filter argument making pods crashing

cloud/services/service/load_balancer.go, cloud/services/service/mock_service/loadbalancer_mock.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_loadbalancer_controller_unit_test.go, controllers/oscmachine_vm_controller.go, controllers/oscmachine_vm_controller_unit_test.go, testenv/osccluster_controller_test.go
Sometimes, a control plane oscmachine is removed from the LBU but vm cannot be deleted.
Next reconciler runs are stuck trying to remove VM from the LBU.
Some unit tests are redundant and are removed. Others are simplified for improved readability.
=> 🐛 fix/oscmachine: unable to delete cp vm if vm is not registered in LBU anymore

controllers/osccluster_internetservice_controller.go, controllers/osccluster_internetservice_controller_unit_test.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_net_controller.go, controllers/osccluster_publicip_controller.go, controllers/osccluster_routetable_controller.go, controllers/osccluster_routetable_controller_unit_test.go, controllers/osccluster_securitygroup_controller.go, controllers/osccluster_securitygroup_controller_unit_test.go, controllers/osccluster_subnet_controller.go, controllers/osccluster_subnet_controller_unit_test.go, controllers/oscmachine_keypair_controller.go
Delete reconciliation could not delete routes because route deletion required an internet service that was deleted just before.
When retrying, the reconciler found no load balancer and stopped the delete reconciliation, removing the finalizer, and leaving all resources that are supposed to be deleted after route tables (security groups, internet services, nets & subnets).
There are multiple places where the finalizer was removed without being sure that all network resources were all deleted.
When deleting an uninitialized cluster, no net id is present in the spec. We need to ensure that reconciliation succeeds. As most resources depend on a net, no deletion is attempted for those without a known net id.
=> 🐛 fix: many network resources were not deleted during delete reconciliation

config/manager/manager.yaml, helm/clusterapioutscale/templates/deployment.yaml, helm/clusterapioutscale/values.yaml, helm/helm_test.go
The same defaults are set everywhere:
- cpu request/limits: 100m
- memory requests/limits: 128Mi
In some places, the default request was above limit.
Chart generation unit tests are added.
=> 🔧 config/helm: set the same resources limits/requests everywhere

helm/clusterapioutscale/values.yaml, util/reconciler/defaults.go
The previous backoff defaults (interval 1s, factor 2, max tries 20) meant retrying for nearly 1 week...
=> ⚡ perfs/backoff: no need for 1 week backoff, default is now 1 min

api/v1beta1/osccluster_validation.go, api/v1beta1/osccluster_webhook_test.go, api/v1beta1/oscclustertemplate_webhook_test.go, api/v1beta1/oscmachine_validation.go, api/v1beta1/oscmachine_webhook_test.go, api/v1beta1/oscmachinetemplate_webhook_test.go
- add more checks in validation webhook
- better field paths in errors (path are not complete but it is better than returning only the field name)
- `ValidateCidr`: no need to do what `net.ParseCIDR` already does
There are still a lot of fields that would require validation -> to be continued.
Validation should also be removed from reconciliation loops, as it has already been done by the webhook. It would simplify reconciliation code.
=> 🦺 validation: more validation, better field paths in errors

cloud/services/compute/mock_compute/vm_mock.go, cloud/services/compute/vm.go, controllers/oscmachinetemplate_capacity_controller.go, controllers/oscmachinetemplate_capacity_controller_unit_test.go, controllers/oscmachinetemplate_controller.go
When implementing scale-to-zero autoscaling, the autoscaler requires having status.capacity in infrastructure machine templates.
The former implementation waited for vms to be up, and queried OAPI to get the vmType.
As the vmType is defined in the spec, we can set status.capacity from the spec. This saves a lot of reconciliations.
This only works with tina machine types, not aws style types, but only tina machine types pass validation.
=> ♻️ refacto/oscmachinetemplate: set status.capacity from vmspec without waiting for vm

example/cluster-machine-template-bastion.yaml, example/cluster-machine-template-simple-taint.yaml, example/cluster-machine-template-simple.yaml, osc-secret.yaml
Summary:
* Add port 2380 to SG and create namespace
Description:
* Security Groups should have port 2380 enabled to allow ETCD Peering
* region: eu-west-2 // region is required i used eu-west-2 as placeholder
* Added namespace creation for the outscale api cluster
@alistarle @airklizz cf
=> Enable port 2380 for ETCD in SG. Add region for osc-secret and create namespace

cloud/utils/utils.go, cloud/utils/utils_test.go
key should be prefixed by "tags."
=> 🐛 fix/vm: tags were incorrectly stored in user data

cloud/services/compute/image.go, cloud/services/compute/vm.go, cloud/services/net/internetservice.go, cloud/services/net/natservice.go, cloud/services/net/net.go, cloud/services/net/subnet.go, cloud/services/security/keypair.go, cloud/services/security/publicip.go, cloud/services/security/route.go, cloud/services/security/securitygroup.go, cloud/services/service/load_balancer.go, cloud/services/storage/volume.go, cloud/utils/errors.go
This PR changes OAPI error messages from:
`cannot create vm: error 400 Bad Request httpRes 400 Bad Request`
to:
`cannot create vm: InvalidResource/5023 (The ImageId 'ami-e1a786f1' doesn't exist.)`
=> 🥅 errors: better error messages from Outscale API

main.go
/kind feature
Add flag to controller to change the default syncPeriod (aka the minimum time between reconciles when no resource has been changed).
Fixes #374 
**TODOs**:
=> feat(controller): Add flag to change the default syncPeriod

controllers/osccluster_controller.go
Cluster API already logs the reconciliation result, no need to log errors...
=> 🔇 logs: remove cluster reconciliation error logs

capm.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_oscmachinetemplates.yaml, config/crd/kustomization.yaml, hack/ensure-controller-gen.sh, helm/clusterapioutscale/templates/crd.yaml, test/e2e/config/outscale.yaml, test/e2e/data/infrastructure-outscale/cluster-template-topology.yaml, test/e2e/data/infrastructure-outscale/clusterclass-cluster-class.yaml, test/e2e/data/infrastructure-outscale/infrastructure-components.yaml, test/e2e/e2e_test.go, test/e2e/node_test.go, test/e2e/quickstart_test.go
* Enable OscClusterTemplate CRD
* Add cluster class e2e test
Be aware that ClusterClass is behind the ClusterTopology feature gate, which might need activation on capi-kubeadm-control-plane-controller-manager and capi-controller-manager
=> 🐛 fix/crd: add missing oscclustertemplate CRD

cloud/services/compute/image.go, cloud/services/compute/vm.go, cloud/services/net/internetservice.go, cloud/services/net/natservice.go, cloud/services/net/net.go, cloud/services/net/subnet.go, cloud/services/security/publicip.go, cloud/services/security/route.go, cloud/services/security/securitygroup.go, cloud/services/service/load_balancer.go, cloud/tag/tag.go, cloud/utils/backoff.go, cloud/utils/errors.go, util/reconciler/defaults.go
Since failed reconciliation loops are automatically retried, most API calls do not require backoff.
However,  Backoff is still necessary for certain secondary calls (e.g. resource tagging): a failed secondary call may cause a duplicate (next reconciliation loop will not find the created resource when searching by tag, and a new one will be created), or a misconfigured resource (e.g. LB healthcheck).
Fixes #475
=> ♻️ refacto/backoff: remove backoff on main calls, secure backoff on secondary calls

api/v1beta1/conditions_consts.go, controllers/osccluster_bastion_controller.go, controllers/osccluster_controller_test.go, controllers/osccluster_internetservice_controller.go, controllers/osccluster_loadbalancer_controller.go, controllers/osccluster_natservice_controller.go, controllers/osccluster_net_controller.go, controllers/osccluster_routetable_controller.go, controllers/osccluster_securitygroup_controller.go, controllers/osccluster_subnet_controller.go, controllers/oscmachine_controller_test.go, controllers/oscmachine_vm_controller.go
No events are currently generated by reconcilers. This adds an event on every IaaS resource creation.
```bash
kubectl describe osccluster.infrastructure.cluster.x-k8s.io/test-cluster-api
[...]
Events:
Type    Reason                  Age   From                   Message
----    ------                  ----  ----                   -------
Normal  NetCreated              11s   osccluster-controller  Net created
Normal  SubnetCreated           10s   osccluster-controller  Subnet created [loadbalancer nat bastion] cloudgouv-eu-west-1a
Normal  SubnetCreated           9s    osccluster-controller  Subnet created [controlplane] cloudgouv-eu-west-1a
Normal  SubnetCreated           8s    osccluster-controller  Subnet created [worker] cloudgouv-eu-west-1a
Normal  InternetServiceCreated  8s …
```
=> ✨ feat: record event on resource creation

cloud/services/compute/image.go, cloud/services/compute/vm.go, cloud/services/net/internetservice.go, cloud/services/net/natservice.go, cloud/services/net/net.go, cloud/services/net/subnet.go, cloud/services/security/publicip.go, cloud/services/security/route.go, cloud/services/security/securitygroup.go, cloud/services/service/load_balancer.go, cloud/tag/tag.go, cloud/utils/errors.go, cloud/utils/errors_test.go, cloud/utils/logging.go
HTTP 409 errors were not properly decoded, and the corresponding error code was not properly logged/stored in status.
=> 🔊 logs: properly decode 409 errors

controllers/oscmachine_controller.go, controllers/oscmachine_controller_test.go, controllers/oscmachine_vm_controller.go
Replacing the former exponential backoff with a linear wait should improve readiness delay.
=> ♻️ refacto/oscmachine: requeue for 30s when waiting for VM to be ready

docs/src/topics/config-security.md, templates/cluster-template-multiaz-secure.yaml, templates/cluster-template-secure.yaml
The management cluster needs access to the workload kube API.
A second var is added to the env required by the secure templates to provide the IP range of the management cluster.
=> 🐛 fix: add missing CAPI IP to secure templates

api/v1beta1/types.go, controllers/osccluster_securitygroup_controller.go
=> 🐛 fix: when ipProtocol=-1, fromPortRange and toPortRange are stored as -1

api/v1beta1/types.go, cloud/utils/utils.go, docs/src/topics/config-cluster.md
Add new service roles to define the subnet to use for loadbalancers (public or internal).
Additional roles are configured for CCM 0.4 compatibility.
Refs #594
=> ✨ feat: add service roles for CCM load balancers

github_actions/deploy_cluster/main.sh
Some E2E tests in other projects assume that the nodes are deployed in subregion a.
We switch back to a to stop breaking those tests.
---
---
---
---
---
=> 👷 ci: switch back to subregion a

cloud/scope/cluster.go, cloud/scope/cluster_test.go, controllers/osccluster_controller_test.go
When the security groups are defined in the spec, allowFromIPRanges/allowToIPRanges would add entries to the spec at each reconciliation, resulting in multiple/infinite duplicates of the allowFromIPRanges/allowToIPRanges rules.
The allowFromIPRanges/allowToIPRanges rules should not be added to the spec.
This also fixes a bug where allowFromIPRanges would allow traffic on port 6443 to the bastion instead of 22.
cc @pli01 
Please check the relevant option(s):
Please describe the test strategy:
=> 🐛 fix(security groups): allowFromIPRanges/allowToIPRanges should not change the security groups spec

controllers/osccluster_controller.go, controllers/oscmachine_controller.go, main.go
CAPOSC now processes multiple OscCluster/OscMachine resources simultaneously.
The PR also adds many new configuration flags:
* `--leader-elect-lease-duration`: Interval at which non-leader candidates will wait to force acquire leadership (previous default: 60s, new default: 15s)
* `--leader-elect-renew-deadline`: Duration that the leading controller manager will retry refreshing leadership before giving up (previous default: 30s, new default: 10s)
* `--leader-elect-retry-period`: Duration that the leading controller manager will retry refreshing leadership before giving up (previous default: 10s, new default: 2s)
* `--reconcile-timeout`: Timeout for reconciles (default: 90m, not changed)
* `--osccluster-concurrency`: Number of OscCluster reconciles to process simultaneously (previous …
=> ⚡️ perfs: add concurrency + tuning config flags
